In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = (r"https://ev-database.org/#group=vehicle-group&rs-pr=10000_100000&rs-er=0_1000&rs-ld=0_1000&rs-ac=2_23&rs-dcfc=0_300&rs-ub=10_200&rs-tw=0_2500&rs-ef=100_350&rs-sa=-1_5&rs-w=1000_3500&rs-c=0_5000&rs-y=2010_2030&s=1&p=0-50")
response=requests.get(url)

In [3]:
response

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

In [5]:
brand=[]
model=[]
price=[]
mileage=[]
battery_capacity=[]
weight=[]

In [6]:
brands=soup.find_all("a", class_="title")
models=soup.find_all("span",class_="model")
prices=soup.find_all("span",class_="country_uk")
mileages=soup.find_all("span",class_="erange_real")
batteries=soup.find_all("span",class_="battery_p")
weights=soup.find_all("span",class_="weight_p")

for b in brands:
    name=b.text.strip().split("\n")[0].split()[0]
    brand.append(name)
for m in models:
    name=m.text.strip()
    model.append(name)
for p in prices:
    name=p.text.strip()
    price.append(name)
for M in mileages:
    name=M.text.strip()
    mileage.append(name)
for B in batteries:
    name=B.text.strip()
    battery_capacity.append(name)
for w in weights:
    name=w.text.strip()
    weight.append(name)

In [7]:
data = {
    "Brand": brand,
    "Model": model,
    "Price": price,
    "Range": mileage,
    "Battery": battery_capacity,
    "Weight": weight,
}

In [8]:
ev=pd.DataFrame(data)

In [9]:
ev

        Brand                       Model    Price   Range    Battery   Weight
0         BMW        iX3 50 xDrive (MY26)  £58,755  610 km  108.7 kWh  2360 kg
1       Volvo              EX60 P6 (MY27)  £56,860  455 km   80.0 kWh  2190 kg
2       Volvo         EX60 P12 AWD (MY27)  £64,860  610 km  112.0 kWh  2405 kg
3         BYD                      ATTO 2  £30,850  245 km   45.1 kWh  1645 kg
4          MG         MG4 Electric 64 kWh  £29,745  360 km   61.7 kWh  1726 kg
...       ...                         ...      ...     ...        ...      ...
1192     Fiat          E-Ulysse L3 50 kWh      N/A  180 km   46.3 kWh  1989 kg
1193   Toyota     Proace Shuttle L 50 kWh      N/A  180 km   46.3 kWh  1989 kg
1194     Opel      Zafira-e Life S 50 kWh      N/A  185 km   46.3 kWh  1932 kg
1195     Ford  e-Tourneo Custom L1 210 kW      N/A  235 km   64.0 kWh  2557 kg
1196  Peugeot  e-Traveller Compact 50 kWh      N/A  185 km   46.3 kWh  1932 kg

[1197 rows x 6 columns]

In [10]:
ev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    1197 non-null   object
 1   Model    1197 non-null   object
 2   Price    1197 non-null   object
 3   Range    1197 non-null   object
 4   Battery  1197 non-null   object
 5   Weight   1197 non-null   object
dtypes: object(6)
memory usage: 56.2+ KB

In [11]:
ev.describe()

                Brand  Model Price   Range   Battery   Weight
count            1197   1197  1197    1197      1197     1197
unique             74   1025   751     109       191      529
top     Mercedes-Benz  e-Up!   N/A  265 km  77.0 kWh  2395 kg
freq              114      4   323      35        63       10

In [12]:
ev.isna().sum()

Brand      0
Model      0
Price      0
Range      0
Battery    0
Weight     0
dtype: int64

In [13]:
ev=ev[ev['Price']!="N/A"]

In [14]:
ev.describe()

             Brand  Model    Price   Range   Battery   Weight
count          874    874      874     874       874      874
unique          56    748      750     100       164      430
top     Volkswagen  e-Up!  £44,990  455 km  77.0 kWh  1530 kg
freq            73      4        9      24        57        9

In [15]:
ev.to_csv("Eletric_vechile.csv",index=False)

In [16]:
pickup=soup.find_all("span",class_="acceleration_p")

In [17]:
zero_to_hundered=[]
for p in pickup:
    name=p.text.replace(",","").replace("sec","").strip()
    zero_to_hundered.append(name)

In [18]:
len(zero_to_hundered)

1197

In [19]:
zero_to_hundered[0:5]

['4.9', '5.9', '3.9', '7.9', '7.9']

In [25]:
data1= {
    "Brand": brand,
    "pickup":zero_to_hundered}

In [26]:
df=pd.DataFrame(data1)

In [27]:
df_csv=df.to_csv("df.csv")